### ISSUE TITLE
snyk/driftctl Orb missing - have to use cloudskiff/driftctl

### ISSUE THREAD

**Issue by mikejk8s** [snyk/driftctl-orb#4]
## Orb version:

1.1.0

## What happened:

I see the snyk/driftctl orb in the registry but CircleCI is unable to find it for some reason. I had to switch to the https://circleci.com/developer/orbs/orb/cloudskiff/driftctl cloudskiff/driftctl orb instead.  The link to the orb in the README points to https://circleci.com/orbs/developer/orb/snyk/driftctl/ which also 404s. I'm not sure if this is related.

## Expected behavior:

I should be able to pull the snyk/driftctl@x.x.x orb per snyks documentation. 

## Additional Information:

I'm a little confused how I see the orb in the registry but can't pull it, maybe I'm actually doing something wrong... Also thanks for making this orb.

**Comment by wbeuil** [comment]
Hey @mikejk8s, thanks for opening this issue.

I opened a PR to update the url in the README since it's the wrong one.

Back to your issue, I don't see why it does not work, any idea here @eliecharra ? I've never tested the orb myself ...

**Comment by eliecharra** [comment]
Thanks for the ping @wbeuil 🙏🏻 I merged your fix in the readme.


@mikejk8s
> I'm a little confused how I see the orb in the registry but can't pull it

Can you elaborate on that, what is exactly the problem ?

**Comment by mikejk8s** [comment]
I have a feeling I typoed the repo.. I'll update when/if I run across it again. But probably safe to assume that was my problem outside of the readme needing the update.

If you can pull it fine just ignore that portion.

Thanks for the readme update!
