### ISSUE TITLE
Add feature to allow input parameters for scan call

### ISSUE THREAD

**Issue by houserx-jinoa** [snyk/driftctl-orb#5]
## Describe Request:
The scan call is not flexible enough for our usage. 

We would like to be able to pass in:
- "--only-unmanaged" 
- "--from tfstate....://......./terraform.tfstate"

## Supporting Documentation Links:
You currently have these options in your CLI usage [here](https://docs.driftctl.com/0.31.0/usage/cmd/scan-usage)

**Comment by eliecharra** [comment]
Hi @houserx-jinoa, driftctl can be configured fully with environment variables.

> We would like to be able to pass in:
>
> "--only-unmanaged"

You can set `DCTL_ONLY_UNMANAGED="true"`

> "--from tfstate....://......./terraform.tfstate"

You can set `DCTL_FROM="tfstate....://......./terraform.tfstate"`

Check here for more details : https://docs.driftctl.com/0.32.0/usage/cmd/scan-usage#options

You can also have a look at [integration test](https://github.com/snyk/driftctl-orb/blob/main/.circleci/config.yml#L26-L36) of this repo for a real example.
